name: Prevent Invalid Commits
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  validate-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check commit message
        run: |
          echo "Checking commit message..."
          if git log -1 --pretty=%B | grep -q "WIP"; then
            echo "❌ WIP commits are not allowed on main!"
            exit 1
          fi
      - name: Run validation script
        run: |
          echo "Running path checks..."
          if git diff --name-only HEAD~1 | grep -q "^config/secrets.yml$"; then
            echo "❌ Direct modification of secrets.yml is not allowed!"
            exit 1
          fi
